version: '3'
services:
  eosio:
    build:
      context: ./blockchain
      dockerfile: Dockerfile-eosio
    # image: eostudio/eos:v2.0.3
    container_name: "eosio"
    # stop_grace_period: 1m
    ports:
      - 8888:8888
    volumes:
      - ./:/var/repo
      - ./temp/eosio:/data
  # mongo:
  #   image: mongo:latest
  #   container_name: "mongodb"
  #   ports:
  #     - 27017:27017
  #   environment:
  #     - MONGO_DATA_DIR=/data
  #     - MONGO_LOG_DIR=/dev/null
  #     - MONGODB_USER="user" 
  #     - MONGODB_PASS="pass"
  #   volumes:
  #     - ./temp/mongo:/data
  # back-end:
  #   image: node
  #   container_name: "back-end"
  #   ports:
  #     - 3000:3000
  #   volumes:
  #    - ./:/var/repo
  #   working_dir: /var/repo/back-end
  #   command:
  #     sh -c 'npm start'